### ISSUE TITLE
Modify README.md file

### ISSUE THREAD

**Issue by 0xNacho** [proteus-h2020/proteus-engine#1]
Please, modify the default ```README.md``` file of Flink to add some instructions about the usage of  the proteus-engine API (what classes / methods you added, how they work, etc.).

It could also be interesting to add a basic installation and deployment guide.

**Comment by VenturaDelMonte** [comment]
Thanks for opening the first issue🥇 ! Do you think a link to a small wiki entry should be enough?
Being a fork of Flink, the very same procedure applies, thus I would suggest to just add a link to Flink deployment guide.

**Comment by 0xNacho** [comment]
WRT to the PROTEUS-ENGINE docs, a wiki should more than enough.

For deployments guidelines, I also agree to add a link to the Flink deployment guidelines.

Thanks a lot, Ventura!

**Comment by VenturaDelMonte** [comment]
@alirezarm created the wiki and I referred the wiki in the repo description. I think we may close this issue.
